# Generated by Django 3.1.7 on 2021-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210624_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='post2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60, null=True)),
                ('desc', models.CharField(default='', max_length=100, null=True)),
                ('date', models.CharField(default='', max_length=20, null=True)),
                ('img', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null='True', upload_to='imagen'),
            preserve_default='True',
        ),
    ]
